pom.xml, src/main/java/com/grepp/codemap/infra/auth/Role.java, src/main/java/com/grepp/codemap/infra/config/ModelMapperConfig.java, src/main/java/com/grepp/codemap/infra/config/SecurityConfig.java, src/main/java/com/grepp/codemap/infra/error/exceptions/CommonException.java, src/main/java/com/grepp/codemap/infra/response/ResponseCode.java, src/main/java/com/grepp/codemap/user/controller/UserController.java, src/main/java/com/grepp/codemap/user/domain/User.java, src/main/java/com/grepp/codemap/user/dto/UserDto.java, src/main/java/com/grepp/codemap/user/form/SigninForm.java, src/main/java/com/grepp/codemap/user/form/SignupForm.java, src/main/java/com/grepp/codemap/user/repository/UserRepository.java, src/main/java/com/grepp/codemap/user/service/UserService.java
- pom.xml : <configuration> 태그로 묶여있는 부분을 지워서 수정했습니다. 추후에 queryDSL 관련해서 플러그인 넣어야할 때는 강사님 코드 그대로 사용하면 될 것 같다고 말씀해주셨습니다.
- infra 패키지 : auth 패키지 하단에 Role 클래스 만들어줬고 그 외에 config, error, response 패키지는 강의 때 사용한 코드 그대로 사용했습니다.
- UserController
- User 엔티티 : @setter 추가 안하고 따로 메서드만 추가
- UserDto
- SigninForm/SignupForm
- UserRepository
- UserService
=> feat : 회원가입 + 로그인

src/main/java/com/grepp/codemap/infra/config/QuerydslConfig.java, src/main/java/com/grepp/codemap/infra/config/SecurityConfig.java, src/main/java/com/grepp/codemap/routine/controller/DailyRoutineController.java, src/main/java/com/grepp/codemap/routine/dto/DailyRoutineDto.java, src/main/java/com/grepp/codemap/routine/dto/PomodoroSessionDto.java, src/main/java/com/grepp/codemap/routine/repository/DailyRoutineRepository.java, src/main/java/com/grepp/codemap/routine/repository/DailyRoutineRepositoryCustom.java, src/main/java/com/grepp/codemap/routine/repository/DailyRoutineRepositoryCustomImpl.java, src/main/java/com/grepp/codemap/routine/repository/PomodoroSessionRepository.java, src/main/java/com/grepp/codemap/routine/service/DailyRoutineService.java, src/main/java/com/grepp/codemap/user/service/UserService.java, src/test/java/com/grepp/codemap/CodeMapApplicationTests.java, src/test/java/com/grepp/codemap/routine/service/DailyRoutineTest.java
=> feat: implemting user routine managing function

src/main/java/com/grepp/codemap/admin/controller/AdminUserController.java, src/main/java/com/grepp/codemap/admin/dto/AdminUserUpdateDto.java, src/main/java/com/grepp/codemap/admin/service/AdminUserService.java
- AdminUserController
- AdminUserUpdateDto
- AdminUserService
=> feat: 관리자 회원 관리 기능

pom.xml, src/main/java/com/grepp/codemap/chatbot/controller/ChatbotController.java, src/main/java/com/grepp/codemap/chatbot/dto/ChatRequestDto.java, src/main/java/com/grepp/codemap/chatbot/dto/ChatResponseDto.java, src/main/java/com/grepp/codemap/chatbot/llm/Assistant.java, src/main/java/com/grepp/codemap/chatbot/service/ChatbotService.java, src/main/java/com/grepp/codemap/infra/config/SecurityConfig.java, src/main/resources/application.properties
feat: Create Chatbot
Create
- ChatbotController
- ChatRequestDto
- ChatResponseDto
- Assistant
- ChatbotService
Update
- SecurityConfig
- application.properties
CSRF 토큰 문제로 인하여 SecurityConfig를 손보았습니다.
=> :sparkles: feat: Create Chatbot

src/main/java/com/grepp/codemap/admin/service/AdminUserService.java
=> refactor: 관리자 회원 관리 기능

src/main/java/com/grepp/codemap/infra/auth/AuthService.java, src/main/java/com/grepp/codemap/infra/config/SecurityConfig.java, src/main/java/com/grepp/codemap/user/controller/UserController.java
- AuthService 추가
- 로그인 + 회원가입 기능 수정 완료
=> feat : 로그인 + 회원가입

src/main/java/com/grepp/codemap/routine/controller/DailyRoutineController.java
routinecontroller userId 불러오는 방식 다른 컨트롤러와 방식 일치시켜놨습니다
=> refactor : matching routinecontroller with other controller method

src/main/java/com/grepp/codemap/user/controller/UserController.java
- 로그인 시 Spring Security와 수동 로그인 방식(Session)을 함께 사용할 수 있도록 SecurityContext를 세션에 직접 저장하는 인증 로직을 구현했습니다.
- 
- 기본 시큐리티 설정 없이 사용자 정의 컨트롤러에서 로그인 처리를 할 경우, 인증 상태를 다음 요청까지 유지하기 위한 수동 처리 방식이 필요합니다.
✅ 요구 사항
- 로그인 후 인증 상태가 유지되어야 하며, 로그인 이후의 페이지(/routines 등)에 접근할 수 있어야 한다.
✅ 구현 내용
- UserService.login(form)을 통해 로그인 처리 후, userId를 세션에 저장
- Spring Security가 인증 상태를 인식할 수 있도록 다음 작업을 추가로 수행
=> refactor: login -> 403 이슈 해결

src/main/java/com/grepp/codemap/routine/controller/DailyRoutineController.java, src/main/resources/application.properties, src/main/resources/templates/routine/routine-list.html
=> feat : add routine-list.html

src/main/java/com/grepp/codemap/routine/controller/DailyRoutineController.java, src/main/java/com/grepp/codemap/routine/service/DailyRoutineService.java, src/main/resources/static/css/sidenav/user/style.css, src/main/resources/templates/fragments/sidenav/user/user-sidenav.html, src/main/resources/templates/routine/routine-list.html
쉬어가기 버튼 클릭 시 루틴 제목 앞에 (PASS) 붙이고, 시작하기 버튼 비활성화, 쉬어가기 취소 시 원래대로 돌아가게 바꿨습니다
=> feat : add routine pass

src/main/java/com/grepp/codemap/infra/auth/AuthService.java, src/main/java/com/grepp/codemap/infra/config/SecurityConfig.java, src/main/java/com/grepp/codemap/interview/controller/InterviewController.java, src/main/java/com/grepp/codemap/interview/domain/InterviewQuestion.java, src/main/java/com/grepp/codemap/interview/service/InterviewService.java, src/main/java/com/grepp/codemap/user/controller/UserController.java, src/main/resources/templates/fragments/sidenav/admin/admin-sidenav.html, src/main/resources/templates/fragments/sidenav/user/user-sidenav.html
관리자 컨텐츠 관리 (면접 질문 crud) 기능 구현
추후에 관리자 sidenav를 포함해서 전체적으로 ui 개선할 예정입니다.
=> refactor : edit admin interviewQuestions func

src/main/resources/templates/fragments/sidenav/user/user-sidenav.html
=> fix : modified to receive user nickname sidenav

src/main/java/com/grepp/codemap/infra/response/ResponseCode.java, src/main/java/com/grepp/codemap/user/controller/UserController.java, src/main/resources/templates/admin/manage-users.html, src/main/resources/templates/admin/user-delete-modal.html, src/main/resources/templates/user/signin.html
관리자 회원 관리
삭제 모달
+ 
로그인 시 회원 정보 잘못 입력 시 경고 메세지 뜨게 구성
=> refactor: created deleting modal for adminUserControlling

src/main/java/com/grepp/codemap/admin/service/AdminUserService.java, src/main/java/com/grepp/codemap/routine/repository/DailyRoutineRepository.java, src/main/java/com/grepp/codemap/routine/repository/PomodoroSessionRepository.java, src/main/java/com/grepp/codemap/todo/repository/TodoRepository.java, src/main/resources/templates/admin/category-select.html, src/main/resources/templates/admin/manage-users.html, src/main/resources/templates/admin/user-delete-modal.html
관리자 회원 관리 기능 중 삭제 기능 수정
관리자 회원 관리 + 컨텐츠 관리 화면 부분 오류 수정
깃 오류로 올라가지 않았던 user-delete-modal 화면 파일 추가
데일리 루틴 (뽀모도로 데이터 포함), 투두 데이터 존재 시 삭제 안되는 오류 수정
pomodoroSessionRepository
dailyRoutineRepository
todoRepository
AdminUserService
=> refactor: modified AdminUserDeleting func

src/main/java/com/grepp/codemap/routine/controller/DailyRoutineController.java, src/main/java/com/grepp/codemap/routine/service/DailyRoutineService.java, src/main/resources/templates/routine/routine-list.html, src/main/resources/templates/routine/timer.html
데일리 루틴, 포모도로 타이머 기능구현, 페이지 연결까지 완료했습니다
=> Daily routine, Pomodoro timer function implement completed

src/main/java/com/grepp/codemap/routine/controller/DailyRoutineController.java, src/main/java/com/grepp/codemap/todo/controller/TodoController.java, src/main/resources/templates/fragments/header/header.html, src/main/resources/templates/routine/routine-list.html, src/main/resources/templates/routine/timer.html
=>  fix : remove window alert page

src/main/java/com/grepp/codemap/interview/controller/InterviewController.java, src/main/resources/templates/interview/interview-select.html, src/main/resources/templates/routine/routine-list.html, src/main/resources/templates/todo/calender.html
=>  fix : interview-select ui

src/main/java/com/grepp/codemap/admin/controller/AdminQuestionController.java, src/main/java/com/grepp/codemap/interview/controller/InterviewController.java, src/main/java/com/grepp/codemap/interview/repository/InterviewRepository.java, src/main/java/com/grepp/codemap/interview/service/InterviewService.java, src/main/resources/templates/admin/content/question-form.html, src/main/resources/templates/interview/interview-random.html, src/main/resources/templates/interview/interview-select.html
사용자 면접 질문 기능 : 
- 카테고리 복수 선택 + 질문 랜덤 5개 출력 으로 기능 수정 완료했습니다.
- 문제풀이 시 난이도 띄워주는 부분이 없어서 카테고리 옆에 난이도 표시했습니다.
관리자 면접 질문 기능 : 문항 추가 안되는 오류 있어서 수정하고 다른 기능도 체크했습니다.
<추후 수정할 내용>
- 전반적 UI 통일 및 개선
- 사용자 면접 질문 풀이 시 몇 번째 문제인지 난이도 옆에 숫자로만 나와있는데 페이지네이션 등으로 처리해서 보여주기
- 관리자 회원 관리 기능에서 회원 정보 수정 시 입력란 중 일부만 수정해도 저장할 수 있게끔 분리할 예정
=> refactor: modified user + admin Question func

src/main/java/com/grepp/codemap/admin/service/AdminUserService.java, src/main/resources/templates/admin/user/edit-users.html
관리자 회원 관리:
- 회원 정보 수정 시, 세 가지 중 일부만 입력해도 수정되게 변경.
=> refactor: modified adminUserControlling func\

src/main/java/com/grepp/codemap/interview/controller/InterviewController.java, src/main/java/com/grepp/codemap/interview/repository/UserAnswerRepository.java, src/main/java/com/grepp/codemap/interview/service/InterviewService.java, src/main/resources/static/css/sidenav/admin/style.css, src/main/resources/templates/admin/user/manage-users.html, src/main/resources/templates/interview/interview-select.html
사용자 면접 질문:
- 등록된 문항이 없는 카테고리를 선택했을 때 에러 메세지 띄워주는 화면 수정
=> refactor: modified userInterviewControlling func

src/main/java/com/grepp/codemap/mypage/controller/MyPageViewController.java, src/main/java/com/grepp/codemap/mypage/dto/UserStatDto.java, src/main/java/com/grepp/codemap/mypage/service/MyPageService.java, src/main/java/com/grepp/codemap/mypage/service/UserStatService.java, src/main/java/com/grepp/codemap/routine/repository/DailyRoutineRepository.java, src/main/java/com/grepp/codemap/user/controller/UserSettingController.java, src/main/resources/application.properties, src/main/resources/data.sql, src/main/resources/templates/fragments/sidenav/user/user-sidenav.html, src/main/resources/templates/mypage/settings.html, src/main/resources/templates/mypage/stats.html
:sparkles: feat: Create MyPage Chart
Create
- MyPageViewController,java
- settings.html
- stat.html
- data.sql
Update
- UserStatDto.java
- MyPageService.java
- UserStatService.java
- DailyRoutineRepository.java
- UserSettingController.java
- user-sidenav.html
- application.properties
=> :sparkles: feat: Create MyPage Chart

src/main/java/com/grepp/codemap/routine/controller/DailyRoutineController.java, src/main/java/com/grepp/codemap/routine/service/DailyRoutineService.java, src/main/resources/init/data.sql, src/main/resources/templates/routine/routine-list.html
=> feat : add date filtering

src/main/java/com/grepp/codemap/mypage/controller/MyPageViewController.java, src/main/java/com/grepp/codemap/mypage/service/MyPageService.java, src/main/java/com/grepp/codemap/todo/repository/TodoRepository.java, src/main/resources/templates/mypage/stats.html
:sparkles: feat: Create MyPage Todo list
Update
- MyPageViewController.java
- MyPageService.java
- TodoRepository.java
- stats.html
=> :sparkles: feat: Create MyPage Todo list

src/main/resources/static/css/sidenav/admin/style.css, src/main/resources/templates/admin/content/category-select.html, src/main/resources/templates/admin/content/question-form.html, src/main/resources/templates/admin/content/question-list.html, src/main/resources/templates/user/signin.html
관리자 컨텐츠 관리
- 질문 등록 / 수정 시 로그아웃 버튼 깨지는 거 수정
로그인
- 비밀번호 표시 토글 및 기능 구현 완료 (-> 아이콘 중간으로 조정하려다 실패)
=> refactor: modified questionForm + signin view

src/main/java/com/grepp/codemap/infra/error/exceptions/CommonException.java, src/main/java/com/grepp/codemap/user/controller/UserController.java, src/main/resources/application.properties, src/main/resources/templates/mypage/settings.html, src/main/resources/templates/mypage/stats.html
Update: Update settings.html
Update
- UserController.java
- settings.html
- stats.html
- application.properties
=> :lipstick: Update: Update settings.html

src/main/resources/templates/mypage/settings.html
환경설정 페이지 UI 개선
UserSettingController 토대로 구현
=> feat: 환경설정 페이지 UI 개선

src/main/java/com/grepp/codemap/routine/controller/DailyRoutineController.java, src/main/resources/application.properties, src/main/resources/templates/routine/routine-list.html
=>  fix  : 루틴 페이지 원상복구

src/main/java/com/grepp/codemap/user/controller/UserSettingController.java, src/main/resources/application.properties, src/main/resources/templates/mypage/settings.html
feat: Create Nickname, Password Change Function
Update
- UserSettingController.java
- settings.html
=> :sparkles: feat: Create Nickname, Password Change Function

src/main/resources/application.properties, src/main/resources/templates/fragments/common/chatbot-modal.html, src/main/resources/templates/interview/interview-answer.html, src/main/resources/templates/interview/interview-random.html, src/main/resources/templates/interview/interview-result.html, src/main/resources/templates/interview/interview-select.html, src/main/resources/templates/mypage/settings.html, src/main/resources/templates/mypage/stats.html, src/main/resources/templates/routine/routine-list.html, src/main/resources/templates/routine/timer.html, src/main/resources/templates/todo/calender.html, src/main/resources/templates/todo/todo-list.html
feat: Create ChatBot modal
Update
- All pages
=> :sparkles: feat: Create ChatBot modal
